### ISSUE TITLE
Uitleg schrijven waarom we deze SDG gekozen hebben.

### ISSUE THREAD

**Issue by joeri2001** [joeri2001/hhs-project-1#1]

**Comment by joeri2001** [comment]
[SDG Omschrijving.docx](https://github.com/user-attachments/files/17229226/SDG.Omschrijving.docx)

**Comment by joeri2001** [comment]
[SDG Omschrijving.docx](https://github.com/user-attachments/files/17229304/SDG.Omschrijving.docx)

**Comment by rochellakaria** [comment]
https://dehaagsehogeschool-my.sharepoint.com/:u:/r/personal/22162445_student_hhs_nl/Documents/BPMN%20Challenge.vsdx?d=w1b4371e9a70a44ad868dd9278f5c8ad8&csf=1&web=1&e=WPGhGh
