### ISSUE TITLE
BMC maken / toelichten

### ISSUE THREAD

**Issue by joeri2001** [joeri2001/hhs-project-1#2]

**Comment by joeri2001** [comment]
[BMC model.docx](https://github.com/user-attachments/files/17240807/BMC.model.docx)

**Comment by Alina-235** [comment]
[BMC model_uitleg.docx](https://github.com/user-attachments/files/17241513/BMC.model_uitleg.docx)

**Comment by MikeAarts06** [comment]
[BMC groep 3.pptx](https://github.com/user-attachments/files/17241559/BMC.groep.3.pptx)

**Comment by Alina-235** [comment]
[BMC model_uitleg nieuw.docx](https://github.com/user-attachments/files/17241755/BMC.model_uitleg.nieuw.docx)
